$(document).ready(()=>{
    $("Resgister_link").click(()=>{
        $("#form1").toggle();
    });
});
$(document).ready(()=>{
    $("Submit").click(()=>{
        $("login").toggle();
    });
});